### ISSUE TITLE
RecyclerView not present in Fragments' xml code

### ISSUE THREAD

**Issue by Lekky71** [corneliuze/Movies-Guide#2]
Most of your fragments do not contain a RecyclerView with the id: "movie_detail_recyclerview",
this is why the fragments are crashing.

- [x] fix this

**Comment by falayy** [comment]
i've fixed this.

**Comment by Lekky71** [comment]
no, fragment_discover_fragments.xml still doesn't have recycler view with id "movie_detail_recyclerview"

- [x] add RecyclerView

**Comment by falayy** [comment]
done
